def print_banner():
    print(r"")
    print(r"Thank you for using")
    print(r"")
    print(r"==================================================")
    print(r"RRRRRRRRRR   EEEEEEEEEEEE                         ")
    print(r"RR      RR   EE                                   ")
    print(r"RR      RR   EE                                   ")
    print(r"RRRRRRRRRR   EEEEEEEEE   yy    yy  eeeee   sssss  ")
    print(r"RR    RR     EE           yy   yy ee   ee ss    s ")
    print(r"RR     RR    EE            yy yy  eeeeee   ss     ")
    print(r"RR      RR   EE              yy   ee         ss   ")
    print(r"RR       RR  EE             yy    ee    e s    ss ")
    print(r"RR        RR EEEEEEEEEEEE  yy      eeeee   sssss  ")
    print(r"==================================================")
    print(r"")